name: meteo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  api_cache_manager: ^1.0.2
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  flutter_screenutil: ^5.9.3
  kiwi: ^5.0.1
  fluttertoast: ^8.2.8
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  geolocator: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
